const SET_EMAIL = 'SET_EMAIL'
const SET_PASSWORD = 'SET_PASSWORD'
const SET_CONFIRM_PASSWORD = 'SET_CONFIRM_PASSWORD'
const SET_SELECTED_QUESTION = 'SET_SELECTED_QUESTION'
const SET_ANSWER = 'SET_ANSWER'
const SET_EMAIL_ERROR = 'SET_EMAIL_ERROR'
const SET_PASSWORD_ERROR = 'SET_PASSWORD_ERROR'
const SET_CONFIRM_PASSWORD_ERROR = 'SET_CONFIRM_PASSWORD_ERROR'
const ENABLE_SET_PASSWORD = 'ENABLE_SET_PASSWORD'
const RESET_STATE = 'RESET_STATE'



export { SET_EMAIL, SET_PASSWORD, SET_CONFIRM_PASSWORD, SET_SELECTED_QUESTION, SET_ANSWER, SET_EMAIL_ERROR, SET_PASSWORD_ERROR, SET_CONFIRM_PASSWORD_ERROR, ENABLE_SET_PASSWORD, RESET_STATE }

