
const SET_EMAIL = 'SET_EMAIL'
const SET_PASSWORD = 'SET_PASSWORD'
const SET_EMAIL_ERROR = 'SET_EMAIL_ERROR'
const RESET_STATE = 'RESET_STATE'


export { SET_EMAIL, SET_PASSWORD, SET_EMAIL_ERROR, RESET_STATE }

